config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
    devise_for :users
    root to: "pages#home"
    resources :products
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
    resources :orders, only: [:show, :create] do
      resources :payments, only: :new
    end
    resources :contacts, only: [:new, :create]
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :phone_number, :question, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :product
  monetize :amount_cents
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/product.rb
class Product < ApplicationRecord
  validates :sku, :name, :description, :price, presence: :true
  has_one_attached :photo
  monetize :price_cents
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  validates :content, presence: :true
  validates :content, length: { maximum: 600 }
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy

  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale
  before_action :store_user_location, if: :storable_location?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def store_user_location
    # Store the current URL as the user's return location
    session[:return_to] = request.referer
  end

  def storable_location?
    # Only store the URL if it's a GET request
    request.get?
  end

  def after_sign_in_path_for(resource_or_scope)
    # If the user has a stored return location, redirect to that page
    if session[:return_to].present?
      session[:return_to]
    else
      # Otherwise, redirect to the default path after login
      super
    end
  end



  def default_url_options
    {locale: I18n.locale}
  end

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ?
      parsed_locale.to_sym :
      nil
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params_contact)

    if @contact.save
      redirect_to  contacts_path(@contact)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def params_contact
    params.require(:contact).permit(:name, :email, :phone_number, :question)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    product= Product.find(params[:product_id])
    order  = Order.create!(product: product, product_sku: product.sku, amount: product.price, state: 'pending', user: current_user)
    session = Stripe::Checkout::Session.create(
      line_items: [{
        price_data: {
          currency: 'myr',
          unit_amount: product.price_cents,
          product_data: {
            name: product.name,
            description: product.description,
          },
        },
        quantity: 1,
      }],
      mode: 'payment',
      success_url: order_url(order),
      cancel_url: order_url(order)

    )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)
  end

  def show
    @order = current_user.orders.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @products = Product.all
    @places = Place.all
    @markers = @places.geocoded.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {place: place}),
        marker_html: render_to_string(partial: "marker")
      }
    end
    @contact = Contact.new
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def new
      @order = current_user.orders.where(state: 'pending').find(params[:order_id])
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
    @markers = @places.geocoded.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude
      }
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @products = Product.all
    @review = Review.new
    @reviews = Review.all
  end

  def show
    @products = Product.all
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params_product)

    if @product.save
      redirect_to  product_path(@product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def params_product
    params.require(:product).permit(:name, :description, :price, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(params_review)
    @review.user = current_user

    if @review.save
      flash[:success] = "Successfully submitted review"
      redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def params_review
    params.require(:review).permit(:content, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<div class="p-1 m-4 text-center">
  <%= simple_form_for @contact do |f| %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone_number %>
    <%= f.input :question %>
    <%= f.button :submit , "Submit"%>
  <% end %>
</div>

app/views/contacts/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guavaaa</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.3.4/dist/aos.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.3.4/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" unless current_page?(new_user_session_path) || current_page?(new_user_registration_path) %>
    <%= yield %>

  </body>
</html>

app/views/orders/show.html.erb
<div class="container-fluid order-container vh-100">

  <div class="row justify-content-around">
    <div class="col-lg-6 order-box p-3">
      <div class=""><%= cl_image_tag @order.product.photo.key, width: 400, height: 300, crop: :fill %></div>
      <div class="m-3 p-3" style="background-color:#FFD95A;">
        <h1>Order #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h1>
        <ul class="list-unstyled">
          <li><strong>ISSUED ON</strong> <%= @order.created_at.to_date %></li>
          <li><strong>Product</strong> <%= @order.product.name %> [<%= @order.product_sku %>]</li>
          <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @order.amount %></li>
          </li>
        </ul>
        <p>Estimated delivery in <strong>2 business days</strong></p>
      </div>
    </div>
  </div>

</div>

app/views/pages/_info_window.html.erb
<h6><%= place.name %></h6>
<hr>
<p class="text-dark"><i class="fa-solid fa-map-pin"></i>  <%= place.address %></p>

app/views/pages/_marker.html.erb
<%= image_tag "guavaa.png", height: 50, width: 70, alt: "Logo" %>

app/views/pages/firsthome.html.erb
<%= render "shared/navbarhome" %>
<%= render "shared/carousell" %>

<%# BACK TO TOP %>
<div class="back-top"
     data-controller="backtop"
     data-action="scroll@window->backtop#updateButton">
  <a href="#"><i class="fa-solid fa-circle-up"></i></a>
</div>
<%# BACK TO TOP %>

<%# ABOUT %>
<div class="container-fluid py-5 full-height" id="about">
  <div class="row vh-100" >
    <div class="col-lg-4 d-none d-lg-block vh-100" style="background-color: #F1F5F2">
      <div class="service p-6 bg-base shadow-effect" data-aos="fade-up"
           style="background-image: url('https://images.unsplash.com/photo-1564322955384-c41858b46881?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=388&q=80');
                  background-size: cover;
                  background-position: center;">
          <%# <a href="#" class="link-custom text-end">Read More</a> %>
      </div>
    </div>
    <div class="col-lg-8 vh-100" style="background-color: #ADC2A9;">
      <section class="about">
        <p class="fw-bold display-7" data-aos="fade-up">About</p>
        <br>
        <h3 class="display-4 fw-bold" data-aos="fade-up">Founder of<span class="text-brand"> <mark>Guavaa</mark></span> From Kampong Sekinchan</h3>
        <p class="lead mt-2 mb-4" data-aos="fade-up" data-aos-delay="300">Transitioning from being a construction worker to a fruit and vegetable farmer is tougher than changing careers to coding. After all, it requires a combination of physical and mental prowess. However, Mr. Pan, driven by an undying spirit, made the courageous decision to convert his rice fields into a sprawling fruit and vegetable garden. He began by cultivating sour kumquats, and then delved into the realms of guava and corn cultivation. It's not mere showmanship; numerous reviews have attested to Mr. Pan's exceptional guavas, and his corn harvests never fail to cause a frenzy. If you want to learn more, read on!</p>
        <div data-aos="fade-up" data-aos-delay="600">
              <a href="#" class="btn btn-brand me-3">See all reviews</a>
              <a href="#" class="link-custom">Email to guavaaa@gmail.com</a>
        </div>
      </section>
    </div>
  </div>
</div>
<%# ABOUT %>

<%# PRODUCTS %>
<%= render "shared/modal" %>
<div class="container-fluid" id="product">
  <div class="row vw-100 vh-50" style="background-color: #61876E;">
  <p class="fw-bold display-6 text-center py-3" data-aos="fade-up"> <%= link_to "Products", products_path %></p>
    <div class="col-lg-4 my-5 py-5" data-aos="fade-up">
      <article class="card mx-auto flex-center">
        <img
          class="card__background"
          src="https://images.unsplash.com/photo-1633349202776-39545fa23de7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
          alt="Photo of Cartagena's cathedral at the background and some colonial style houses"
          width="1920"
          height="2193"
        />
        <div class="card__content | flow">
          <div class="card__content--container | flow">
            <h2 class="card__title"><%= @products.first.name %></h2>
            <p class="card__description">
              <%= @products.first.description.split(". ").first %>
            </p>
          </div>
          <a href=<%= "/products/#{@products.first.id}" %> class="card__button">Read more</a>
        </div>
      </article>
    </div>

    <div class="col-lg-4 my-5 py-5">
      <article class="card mx-auto flex-center" data-aos="fade-up">
        <img
          class="card__background"
          src="https://images.unsplash.com/photo-1629367308496-a2496ba22f88?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80"
          alt="Photo of Cartagena's cathedral at the background and some colonial style houses"
          width="1920"
          height="2193"
        />
        <div class="card__content | flow">
          <div class="card__content--container | flow">
            <h2 class="card__title"><%= @products.second.name %></h2>
            <p class="card__description">
              <%= @products.second.description.split(". ").first %>
            </p>
          </div>
           <a href=<%= "/products/#{@products.second.id}" %> class="card__button">Read more</a>
        </div>
      </article>
    </div>

    <div class="col-lg-4 my-5 py-5">
      <article class="card mx-auto flex-center" data-aos="fade-up">
        <img
          class="card__background"
          src="https://images.unsplash.com/photo-1571646302210-db7990b30751?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
          alt="Photo of Cartagena's cathedral at the background and some colonial style houses"
          width="1920"
          height="2193"
        />
        <div class="card__content | flow">
          <div class="card__content--container | flow">
            <h2 class="card__title"><%= @products.last.name %></h2>
            <p class="card__description">
              <%= @products.last.description.split(". ").first %>
            </p>
          </div>
          <a href=<%= "/products/#{@products.last.id}" %> class="card__button">Read more</a>
        </div>
      </article>
    </div>
  </div>
</div>
<%# PRODUCTS %>

<%# REVIEWS %>
<div class="container-fluid" id="about">
  <div class="row g-4 vh-100 flex justify-content-around align-items-center" >
    <%= render "shared/review" %>
  </div>
</div>
<%# REVIEWS %>

app/views/pages/home.html.erb
<%# HEADER/BANNER/NAVBAR %>
<div class="header">
  <div class="wrapper">
    <div class="row flex justify-content-between align-items-center py-3">
      <div class="col-lg-6 col-md-12 col-sm-12">
        <%= image_tag(asset_path('guavaa.png'), class: "logo-img") %>
     </div>
     <div class="col-lg-6 col-md-12 col-sm-12" >
        <ul class="nav-area">
          <li><a href="#"><%= t("pages.home.home") %></a></li>
          <li><a href="#about"><%= t("pages.home.about") %></a></li>
          <li><a href="#products"><%= t("pages.home.products") %></a></li>
          <li><a href="#"><%= t("pages.home.FAQ") %></a></li>
          <li><a href="#contacts"><%= t("pages.home.contacts") %></a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="welcome-text">
    <h1><%= t '.header' %></h1>
    <p class="text-white"><%= t '.slogan' %></p>
    <a href="/users/sign_up"><%= t '.register' %></a>
  </div>
</div>

<%# BACK TO TOP %>
<div class="back-top float-end"
    data-controller="backtop"
    data-action="scroll@window->backtop#updateButton">
  <a href="#" style="color: #A9907E;"><i class="fa-solid fa-circle-up button-top"></i></a>
</div>
<%# BACK TO TOP %>
<%# HEADER/BANNER/NAVBAR %>

<%# About %>
<div class="about" id="about">
  <div class="container-fluid py-5">
    <h4 class="fw-bold display-5 text-center py-3" data-aos="fade-up"><%= t '.about-content' %></h4>
    <div class="about-row row d-flex p-2 g-3 justify-content-around align-items-center">
      <div class="col-lg-6 col-md-12 col-sm-12" data-aos="fade-right">
        <p class="text-dark text-center about-text"><%= t '.about-content-first' %></p>
      </div>
      <div class="col-lg-3 col-md-12 col-sm-12 bg-white">
        <div class="about-img shadow-effect" data-aos="fade-up" style="background-image: url('https://images.pexels.com/photos/1459331/pexels-photo-1459331.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');">
        </div>
      </div>
    </div>
    <div class="about-row row d-flex p-2 g-3 justify-content-around align-items-center">
      <div class="col-lg-3 col-md-12 col-sm-12">
        <div class="about-img shadow-effect" data-aos="fade-up" style="background-image: url('https://images.pexels.com/photos/8668727/pexels-photo-8668727.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');">
        </div>
      </div>
      <div class="col-lg-6 col-md-12 col-sm-12 bg-white" data-aos="fade-left">
        <p class="text-dark text-center about-text"><%= t '.about-content-second' %></p>
      </div>
    </div>
    <div class="about-row row d-flex p-2 g-3 justify-content-around align-items-center">
      <div class="col-lg-6 col-md-12 col-sm-12" data-aos="fade-right">
        <p class="text-dark text-center about-text"><%= t '.about-content-third' %></p>
      </div>
      <div class="col-lg-3 col-md-12 col-sm-12 bg-white">
        <div class="about-img shadow-effect" data-aos="fade-up" style="background-image: url('https://images.pexels.com/photos/8668726/pexels-photo-8668726.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');">
        </div>
      </div>
    </div>
  </div>
</div>
<%# About %>

<%# PRODUCTS %>
<div class="container-fluid" id="products">
  <div class="row vw-100 vh-50" style="background-color: #F7D060;">
  <h4 class="fw-bold display-5 text-center py-3" data-aos="fade-up"><%= t '.about-content' %></h4>
    <div class="col-lg-4 col-md-12 py-5" data-aos="fade-up">
      <article class="card mx-auto flex-center">
        <img
          class="card__background"
          src="https://images.unsplash.com/photo-1633349202776-39545fa23de7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
          alt="Photo of Cartagena's cathedral at the background and some colonial style houses"
          width="1920"
          height="2193"
        />
        <div class="card__content | flow">
          <div class="card__content--container | flow">
            <h2 class="card__title"><%= t '.product1' %></h2>
            <p class="card__description">
              <%= t '.product1-description' %>
            </p>
          </div>
          <a href=<%= "/products" %> class="card__button fw-bold text-dark text-decoration-none"><%= t '.readmore' %></a>
        </div>
      </article>
    </div>

    <div class="col-lg-4 col-md-12 py-5">
      <article class="card mx-auto flex-center" data-aos="fade-up">
        <img
          class="card__background"
          src="https://images.unsplash.com/photo-1629367308496-a2496ba22f88?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80"
          alt="Photo of Cartagena's cathedral at the background and some colonial style houses"
          width="1920"
          height="2193"
        />
        <div class="card__content | flow">
          <div class="card__content--container | flow">
            <h2 class="card__title"><%= t '.product2' %></h2>
            <p class="card__description">
              <%= t '.product2-description' %>
            </p>
          </div>
           <a href=<%= "/products" %> class="card__button fw-bold text-dark text-decoration-none"><%= t '.readmore' %></a>
        </div>
      </article>
    </div>

    <div class="col-lg-4 col-md-12 py-5">
      <article class="card mx-auto flex-center" data-aos="fade-up">
        <img
          class="card__background"
          src="https://images.unsplash.com/photo-1571646302210-db7990b30751?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
          alt="Photo of Cartagena's cathedral at the background and some colonial style houses"
          width="1920"
          height="2193"
        />
        <div class="card__content | flow">
          <div class="card__content--container | flow">
            <h2 class="card__title"><%= t '.product3' %></h2>
            <p class="card__description">
              <%= t '.product3-description' %>
            </p>
          </div>
          <a href=<%= "/products" %> class="card__button fw-bold text-dark text-decoration-none"><%= t '.readmore' %></a>
        </div>
      </article>
    </div>
  </div>
</div>
<%# PRODUCTS %>

<%# CONTACT US %>
<div class="container" id="contacts">
  <div class="row d-flex g-lg-5 py-5 justify-content-between align-items-center">
    <div class="col-lg-6 p-5 map" data-aos="fade-right">
      <div style="width: 100%; height: 600px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class="col-lg-6 flex flex-column" data-aos="fade-left">
      <div class="row g-2 py-3 flex justify-content-between align-items-center">
        <div class="col-lg-3 p-2 contact-icon text-center"><p><i class="fa-solid fa-phone"></i> <br>03-32410678 | 017-5556677</p></div>
        <div class="col-lg-4 p-2 contact-icon text-center"><p><i class="fa-solid fa-at"></i> <br>guavaaa1788@gmail.com | guavaaa1788@hotmail.com</p></div>
        <div class="col-lg-3 p-2 contact-icon text-center"><p><i class="fa-solid fa-location-dot"></i> <br>Site A, Sekinchan, Selangor</p></div>
      </div>
      <hr>
      <div class="contact p-1">
        <div class="bg-white m-3">
          <h1 class="text-center"><%= t '.contact' %></h1>
          <%= render "contacts/form" %>
        </div>
      </div>
    </div>
  </div>
</div>
<%# CONTACT US %>

<%# FOOTER %>
<%= render "shared/footer" %>
<%# FOOTER %>

app/views/places/index.html.erb
<div style="width: 100%; height: 600px;"
     data-controller="map"
     data-map-markers-value="<%= @markers.to_json %>"
     data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<div class="container-fluid overall-background">
  <%# <div class="row d-flex justify-content-between bg-dark py-2">
    <a href="/#product" class="text-end fs-4" style="color: white;"><i class="fa-regular fa-circle-xmark"></i></a>
  </div> %>
  <div class="container p-5">
    <div class="row d-flex justify-content-between p-3">
      <ol class="breadcrumb w-10 p-3">
        <li class="breadcrumb-item "><a href="/" class="text-white">Home</a></li>
        <li class="breadcrumb-item text-white fw-bold active" aria-current="page">Products</li>
        <li class="breadcrumb-item" aria-current="page"><a href="#review" class="text-white">Reviews</a></li></li>
      </ol>

        <div class="row d-flex g-3 justify-content-between align-items-center">
          <% @products.each do |product| %>
            <div class="col-lg-4 p-2">
              <div class="card h-100">
                <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill, class: "card-img-top" %>
                  <div class="card-body">
                  <h3 class="card-title text-center text-white"><%= product.name %></h3>
                  <p class="card-text text-center">
                    <%= product.description %>
                  </p>
                  <div class="card-footer text-center mt-4">
                    <p><%= humanized_money_with_symbol(product.price) %> /kg</p>
                    <%= form_with url: orders_path do %>
                      <%= hidden_field_tag 'product_id', product.id %>
                      <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>

    </div>
  </div>
</div>

<%# DISPLAYING REVIEWS %>
<div class="container-fluid" id="review" style="background-color:#F9F5F6;">
  <div class="row p-5 justify-content-between align-items-center" data-controller="slideshow" data-slideshow-reviews-value= <%= "#{@reviews.count}"  %> data-slideshow-index-value= <%= "#{@reviews.count - 1}" %>>
    <div class="col-1">
      <a class="text-decoration-none fs-3" data-action="slideshow#previous"><i class="fa-solid fa-chevron-left"></i></a>
    </div>

    <div class="col-10 p-5 text-center">
      <% @reviews.each do |review| %>
      <div data-slideshow-target="slide" class="text-center" data-bs-interval="10000">
        <% if review.photo.key.nil? %>
          <img width="200" height="200"  alt="avatar-large" src="https://images.pexels.com/photos/2134037/pexels-photo-2134037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" style="object-fit:cover;"/>
        <% else %>
          <%= cl_image_tag review.photo.key, height: 200, width: 200, crop: :fill %>
        <% end %>
        <h6 class="p-5">
          <i class="fa-solid fa-quote-left"></i>
          <%= review.content %>
          <i class="fa-solid fa-quote-right"></i>
        </h6>
        <p class="text-dark">--<%= review.user.username %>--</p>
      </div>
      <% end %>
    </div>

    <div class="col-1">
    <a class="fs-3" data-action="slideshow#next"><i class="fa-solid fa-chevron-right"></i></a>
    </div>

  </div>

</div>
<%# DISPLAYING REVIEWS %>

<%# REVIEW NEW FORM %>
<%= render "reviews/form" %>
<%# REVIEW NEW FORM %>


<%# <a href="/#product" class="text-end fs-4"><i class="fa-solid fa-cart-shopping"></i></a> %>
<%# <%= render "slideshow" %>
<!-- Copyright -->
<div class="text-center p-3" style="background-color: #2C3333">
  © 2023 Copyright:
  <a class="text-white" href="/">Guavaaa.com</a>
</div>
<!-- Copyright -->

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

app/views/products/show.html.erb
<%= render "slideshow" %>
<%# <a href="/#product" class="text-end fs-4"><i class="fa-solid fa-cart-shopping"></i></a> %>
<%# <%= render "slideshow" %>

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Please confirm your order!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p><strong>**Noted on this is self pick-up service!**</strong></p>
      </div>
      <div class="modal-footer">
        <%= form_tag orders_path do %>
          <%= hidden_field_tag 'cart_id', @cart.id %>
          <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>